### ISSUE TITLE
Automatic remove of conflicting packages not working

### ISSUE THREAD

**Issue by shadowscott** [zbrateam/Zebra#1143]
**Describe the bug**
Zebra does not suggest to auto remove a conflicting tweak. 

**To Reproduce**
1. Install flex 3 beta from delta beta repo. 
2. Try to install flex 3 and it says it cannot due to conflict. 

**Expected behavior**
Show that it will remove flex 3 beta like cydia does as well as other tweaks that conflict in zebra. 
Ex: install Filza from beta repo. Then attempt to install filza 64bit from beta. This prompts that it will remove the first installed version and replace it with the new one. 

**Device Information (please complete the following information):**
 - iOS Version [e.g. 12.1.2 or 10.3.3]: 13.3.1
 - Zebra Version [e.g. 1.0\~beta1 or beta1]: 1.1b7
 - Device Type [e.g. iPhone or iPad]: iPhone
 - Jailbreak Type [e.g. unc0ver, Chimera, checkra1n, etc.]: Checkra1n 

**Crash Log or System Log**
Please provide a Crash Log to help us solve the issue.

**Additional context**

**Comment by eve0415** [comment]
As this issue is related, I’ll just write here.

Also, Zebra doesn’t suggest for a package to be remove some conflicts dependency package(If you know what I mean)
For example,
1. Install snowboard as well as snowboard’s extension.
2. Put iThemer into queue as install.
3. You’ll see iThemer is marked as install as well as snowboard marked as remove, however, snowboard extensions are not marked as remove but still need to be removed because snowboard is getting remove.

**Comment by wstyres** [comment]
@eve0415 Don't think I can do anything about that, correct me if I'm wrong but Cydia would also have this behavior. The SnowBoard extensions depend on "snowboard" and iThemer provides "SnowBoard". Since iThemer Provides SnowBoard and the extensions depend on SnowBoard, the dependency is now satisfied by iThemer and thus the extensions are not removed.

**Comment by eve0415** [comment]
![AA5F041A-7B49-4004-AF92-79ED7598098A](https://user-images.githubusercontent.com/40632436/80323198-f6fb6880-8864-11ea-9de9-aaf013510c71.png)

I really can’t say anything as I don’t know how cydia works but cydia does put snowboard extensions in queue as remove

**Comment by shadowscott** [comment]
@wstyres any idea on why flex doesn't work the same as cydia in zebra? I'm able to replicate it with flex but don't usually see it with others.

**Comment by wstyres** [comment]
Resolved in 2.0 alpha.
