### ISSUE TITLE
Option to use system sources.list.d for shared sources across package managers

### ISSUE THREAD

**Issue by marijuanARM** [zbrateam/Zebra#1369]
With the release of Odysseyra1n, I'd love to see an option to use the system sources.list.d so that sources can be shared between package managers. Sileo and Cydia already share sources, and to see Zebra included would be nice as well.

**Comment by p0358** [comment]
On chimera1n? Because afaik they don't share them on checkra1n:
https://github.com/wstyres/Zebra/blob/93b3ca9fa7ea3ffa3af5b06000dd52f06dd71d29/Zebra/Tabs/Home/Community%20Sources/ZBCommunitySourcesTableViewController.m#L148

But that would be good nonetheless, I was considering just today writing some tweak that'd let us batch-add a repo to all package managers at once
