### ISSUE TITLE
Hidden Package

### ISSUE THREAD

**Issue by zsxdcfvgbh** [zbrateam/Zebra#1543]
Hello.
This is an issue that happened in Zebra 1.2 beta4a

I have an iPad 7.5.
iPadOS 13.7
Checkra1n
environment.

The package screen and update screen are not shown in the screenshot.
Please fix it.
![E1999E34-FBCC-4E1C-966A-2088CB489A04](https://user-images.githubusercontent.com/61008415/92980525-94cc9880-f4d1-11ea-97a6-065e1c24a34b.png)
![9FE5749A-F7F6-464A-825B-862E6C1FEA4B](https://user-images.githubusercontent.com/61008415/92980532-9ac27980-f4d1-11ea-840a-e6b465eb5d61.png)

**Comment by wstyres** [comment]
Did you just upgrade Zebra from a stable version (1.1.13 or below) by chance?

**Comment by respiredev** [comment]
This also happened to me on my iPhone 8+ on IOS 13.5.1 running odysseyra1n.
This happens when you upgrade from stable (1.1.13) to beta 1.2-4c.
The sources don't refresh and the packages tab goes blank. 

I've tried Resetting the source cache. This brings up a black screen where the sources would usually populate as they refresh. It doesn't. Running sudo apt-get update in terminal also doesn't help.

A fix to this issue is to upgrade from stable 1.1.13 to beta 1.2-4b or earlier, and then upgrade to 1.2-4c

**Comment by wstyres** [comment]
Should be fixed as of 3d4ac2cfa5ff8c3ff7bf8a97e3fbbd0bc1c1e14e.
