### ISSUE TITLE
Releases from /r/jailbreak are not shown in Changes Tab

### ISSUE THREAD

**Issue by anynon** [zbrateam/Zebra#1707]
**Describe the bug**
Updates and News are shown in the Changes tab from Reddit/r/jailbreak, but releases are not shown.

**To Reproduce**
Open the Changes tab 

**Expected behavior**
Free and Paid releases to be shown 

**Device Information:** 

 - iOS Version: iOS 14.2
 - Zebra Version: 1.1.15
 - Device Type: iPhone
 - Jailbreak Type: checkra1n

**Comment by anynon** [comment]
According to this, https://github.com/zbrateam/Zebra/blob/114b082c153e88d9e4219bad7c8c2386cdca579a/Zebra/Tabs/Changes/ZBChangesTableViewController.m#L68 they should be included

**Comment by wstyres** [comment]
This issue has already been fixed in the 1.2 betas of Zebra. The jailbreak reddit has switched from "release" to "free release" and "paid release" so we had to modify our tag as seen here: https://github.com/zbrateam/Zebra/blob/1.2/Zebra/Tabs/Changes/ZBChangesTableViewController.m#L74.

Our development is focused on the 1.2 version so we won't be fixing this problem for 1.1.15.
