### ISSUE TITLE
Search enhancement

### ISSUE THREAD

**Issue by KadenT8** [zbrateam/Zebra#192]
I got the modmyi through community repos and when searching zeppelin it comes up with a bunch of packs but not the actual tweak. Is there a way to refine the search to just what Im looking for?

**Comment by MrJeffery907** [comment]
One idea to fix this is you could add “quotations” around it and then it will only search for that specific phrase

**Comment by worldlydev** [comment]
I agree that search filters should be added. I use them all the time in Google Search and feel that they are underutilized by many. This would go a long way towards making Zebra my preferred package manager which is something I want to happen due to Cydia feeling clunky and looking outdated. It would also be nice to avoid Sileo due to all the drama CoolStar always seems to be involved in. 

Although you should perhaps update your issue as this isn’t a bug at all and rather just an annoyance. This would fall under the enhancement label.

**Comment by worldlydev** [comment]
I was thinking something along the lines of this:
![ZebraSearchFilter](https://user-images.githubusercontent.com/51668635/59616341-85bb3700-9124-11e9-8cbd-05049e554106.jpg)

The ability to filter your search to Type (theme, font, tweak, etc), Source (BigBoss, Packix, etc), Developer (Nepeta, Spark,etc) and Time (last update) is in my opinion the ultimate tool for a power user such as me.

Adding small features like this would definitely make Zebra my favorite package manager. Not to say that it isn't already 😉

**Comment by worldlydev** [comment]
Think filters should be added to changes-, packages- and search tab. 

https://reddit.com/r/jailbreak/comments/e3o40z/request_zebra_dev_please_add_option_to_hide/

#61

**Comment by worldlydev** [comment]
Somewhat related so I didn't want to open a new issue on GitHub.

Add the old section visibility feature from Cydia to Zebra? Configurable in settings or the sources page.

https://imgur.com/a/XWOTN9a
