### ISSUE TITLE
Pull to search

### ISSUE THREAD

**Issue by Sohailwahab** [zbrateam/Zebra#630]
It’s simply a feature that should’ve been everywhere within iOS that contains a search bar on top of the UI. 

FEATURE REQUEST: Pull down in the middle of the search interface to focus on search and bring up they keyboard.

**Comment by JakeValenzuela** [comment]
Search should also be available when inside a repository.

**Comment by worldlydev** [comment]
> Search should also be available when inside a repository.

Came here to say this since my issue was closed in favor of this one. There should be pull to search from within individual packages and from the packages tab (such as Sileo).

----

Also a minor update. Totally understand if this is a no since the string becomes longer but...

I have a suggestion for the "Search for packages" string. I think you should follow Apple's design and change the search text to something that gives multiple examples of what you can search for. Such as in the app store which says you can search for "games, apps, etc". Perhaps "Search for tweaks, themes, widgets, etc".

![D7DBA048-FAEE-4806-883D-589DDAFCA6AD](https://user-images.githubusercontent.com/51668635/71192848-54652480-2289-11ea-9564-8f493cc29e47.jpeg)
